/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TakvimRouteImport } from './routes/takvim'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MizanRouteImport } from './routes/mizan'
import { Route as GundemlerRouteImport } from './routes/gundemler'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MizanIndexRouteImport } from './routes/mizan.index'
import { Route as MizanManeviyatRouteImport } from './routes/mizan.maneviyat'
import { Route as MizanDunyeviRouteImport } from './routes/mizan.dunyevi'
import { Route as MizanAkademiRouteImport } from './routes/mizan.akademi'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MizanRoute = MizanRouteImport.update({
  id: '/mizan',
  path: '/mizan',
  getParentRoute: () => rootRouteImport,
} as any)
const GundemlerRoute = GundemlerRouteImport.update({
  id: '/gundemler',
  path: '/gundemler',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MizanIndexRoute = MizanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MizanRoute,
} as any)
const MizanManeviyatRoute = MizanManeviyatRouteImport.update({
  id: '/maneviyat',
  path: '/maneviyat',
  getParentRoute: () => MizanRoute,
} as any)
const MizanDunyeviRoute = MizanDunyeviRouteImport.update({
  id: '/dunyevi',
  path: '/dunyevi',
  getParentRoute: () => MizanRoute,
} as any)
const MizanAkademiRoute = MizanAkademiRouteImport.update({
  id: '/akademi',
  path: '/akademi',
  getParentRoute: () => MizanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/gundemler': typeof GundemlerRoute
  '/mizan': typeof MizanRouteWithChildren
  '/network': typeof NetworkRoute
  '/takvim': typeof TakvimRoute
  '/workspace': typeof WorkspaceRoute
  '/mizan/akademi': typeof MizanAkademiRoute
  '/mizan/dunyevi': typeof MizanDunyeviRoute
  '/mizan/maneviyat': typeof MizanManeviyatRoute
  '/mizan/': typeof MizanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/gundemler': typeof GundemlerRoute
  '/network': typeof NetworkRoute
  '/takvim': typeof TakvimRoute
  '/workspace': typeof WorkspaceRoute
  '/mizan/akademi': typeof MizanAkademiRoute
  '/mizan/dunyevi': typeof MizanDunyeviRoute
  '/mizan/maneviyat': typeof MizanManeviyatRoute
  '/mizan': typeof MizanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/gundemler': typeof GundemlerRoute
  '/mizan': typeof MizanRouteWithChildren
  '/network': typeof NetworkRoute
  '/takvim': typeof TakvimRoute
  '/workspace': typeof WorkspaceRoute
  '/mizan/akademi': typeof MizanAkademiRoute
  '/mizan/dunyevi': typeof MizanDunyeviRoute
  '/mizan/maneviyat': typeof MizanManeviyatRoute
  '/mizan/': typeof MizanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/gundemler'
    | '/mizan'
    | '/network'
    | '/takvim'
    | '/workspace'
    | '/mizan/akademi'
    | '/mizan/dunyevi'
    | '/mizan/maneviyat'
    | '/mizan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/giris'
    | '/gundemler'
    | '/network'
    | '/takvim'
    | '/workspace'
    | '/mizan/akademi'
    | '/mizan/dunyevi'
    | '/mizan/maneviyat'
    | '/mizan'
  id:
    | '__root__'
    | '/'
    | '/giris'
    | '/gundemler'
    | '/mizan'
    | '/network'
    | '/takvim'
    | '/workspace'
    | '/mizan/akademi'
    | '/mizan/dunyevi'
    | '/mizan/maneviyat'
    | '/mizan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GirisRoute: typeof GirisRoute
  GundemlerRoute: typeof GundemlerRoute
  MizanRoute: typeof MizanRouteWithChildren
  NetworkRoute: typeof NetworkRoute
  TakvimRoute: typeof TakvimRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mizan': {
      id: '/mizan'
      path: '/mizan'
      fullPath: '/mizan'
      preLoaderRoute: typeof MizanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gundemler': {
      id: '/gundemler'
      path: '/gundemler'
      fullPath: '/gundemler'
      preLoaderRoute: typeof GundemlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mizan/': {
      id: '/mizan/'
      path: '/'
      fullPath: '/mizan/'
      preLoaderRoute: typeof MizanIndexRouteImport
      parentRoute: typeof MizanRoute
    }
    '/mizan/maneviyat': {
      id: '/mizan/maneviyat'
      path: '/maneviyat'
      fullPath: '/mizan/maneviyat'
      preLoaderRoute: typeof MizanManeviyatRouteImport
      parentRoute: typeof MizanRoute
    }
    '/mizan/dunyevi': {
      id: '/mizan/dunyevi'
      path: '/dunyevi'
      fullPath: '/mizan/dunyevi'
      preLoaderRoute: typeof MizanDunyeviRouteImport
      parentRoute: typeof MizanRoute
    }
    '/mizan/akademi': {
      id: '/mizan/akademi'
      path: '/akademi'
      fullPath: '/mizan/akademi'
      preLoaderRoute: typeof MizanAkademiRouteImport
      parentRoute: typeof MizanRoute
    }
  }
}

interface MizanRouteChildren {
  MizanAkademiRoute: typeof MizanAkademiRoute
  MizanDunyeviRoute: typeof MizanDunyeviRoute
  MizanManeviyatRoute: typeof MizanManeviyatRoute
  MizanIndexRoute: typeof MizanIndexRoute
}

const MizanRouteChildren: MizanRouteChildren = {
  MizanAkademiRoute: MizanAkademiRoute,
  MizanDunyeviRoute: MizanDunyeviRoute,
  MizanManeviyatRoute: MizanManeviyatRoute,
  MizanIndexRoute: MizanIndexRoute,
}

const MizanRouteWithChildren = MizanRoute._addFileChildren(MizanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GirisRoute: GirisRoute,
  GundemlerRoute: GundemlerRoute,
  MizanRoute: MizanRouteWithChildren,
  NetworkRoute: NetworkRoute,
  TakvimRoute: TakvimRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
